name: build-and-deploy-angular

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: ProductCatalog   # your Azure Web App name
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Angular tests (headless Chrome)
      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # 5. Build Angular app (prod mode)
      - name: Build Angular app
        run: npm run build -- --configuration production

      # 6. Copy web.config + prepare zip
      - name: Prepare artifact
        run: |
          cp web.config dist/
          cd dist
          zip -r ../app.zip .
        shell: bash

      # 7. Login to Azure (OIDC)
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 8. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip
